### PR TITLE
Update TFLite implementation with ByteBufferGlEffect

### PR DESCRIPTION
**Pull request by droid-girl**
Update TFLite/RTLite effect with the new ByteBufferGlEffect

### CODE REVIEW

**Comment by calren** [comment]
can we also update the ultrahdr dependency?

it looks like the test failures from CI are valid:

```
Dependency 'androidx.media3:media3-datasource:1.5.0-alpha01' requires libraries and applications that
           depend on it to compile against version 35 or later of the
           Android APIs.
     
           :samples:media:ultrahdr is currently compiled against android-34.
```

**Comment by calren** [comment]
i just merged https://github.com/android/platform-samples/pull/215. Do you mind rebasing from`main` to see if the build passes now? Thanks!

**Comment by Joseantoniomaypuc** [comment]
> Acabo de fusionar [el n.° 215.](https://github.com/android/platform-samples/pull/215) ¿Te importaría volver a crearlo `main`para ver si la compilación funciona correctamente? ¡Gracias!

Si claro

**Comment by droid-girl** [comment]
Rebased, I do not see any tests running

**Comment by calren** [comment]
thanks for rebasing! i think the tests don't run until a reviewer initially approves it. i kicked it off and looks like the build passed!

**Review by calren — APPROVED** [review]

**Pull request merged**
